### ISSUE TITLE
what happens to `est.incidence()` when `standardize = FALSE` in `load_pop_data()`? I suspect it will break.

### ISSUE THREAD

**Issue by d-morrison** [UCD-SEG/serocalculator#126]
what happens here when `standardize = FALSE` in `load_pop_data()`? I suspect it will break. 

Please write unit tests for `est.incidence()` under both scenarios (`standardize = FALSE` and `standardize = TRUE`)

_Originally posted by @d-morrison in https://github.com/UCD-SERG/serocalculator/pull/119#discussion_r1583969288_

**Comment by chrisorwa** [comment]
There's an error when standardize = FALSE 
`Error in check_pop_data(pop_data = data) : Argument `pop_data` is missing column `age` (age, in years).`

**Comment by chrisorwa** [comment]
`Error:
! Test failed
Backtrace:
    x
 1. +-testthat::test_that(...)
 2. | \-withr (local) `<fn>`()
 3. \-reporter$stop_if_needed()
 4.   \-rlang::abort("Test failed", call = NULL)`

**Comment by chrisorwa** [comment]
@d-morrison I have found a solution. On `est.incidence` the code now checks for the standardized column or the provided column. If `standardize = FALSE` then the code will use the provided column.

`pop_data = pop_data %>%
    dplyr::filter(.data$antigen_iso %in% antigen_isos) %>%
    dplyr::select(dplyr::any_of(c("value",attributes(pop_data)$value_var)),
                  dplyr::any_of(c("age",attributes(pop_data)$age)),
                              "antigen_iso") %>%
    tidyr::drop_na()`
    
I made a similar change to `check_pop_data` so that it checks for standardized or provided column.

`if (!or(x = is.element("age", names(pop_data)), y = is.element(attributes(pop_data)$age_var,names(pop_data)))) {
    stop("Argument `pop_data` is missing column `age` (age, in years).")
  }`

I wrote a unit test for  `est.incidence` and it's now passes the test.
